version: "3"
services:
  mongo:
    image: mongo:4.4.3-bionic
    container_name: mongo_container
    ports:
      - 27018:27017
    logging:
      driver: "none"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  # the KnowRob container
  knowrob:
    container_name: knowrob_container
    build:
      context: .
    depends_on:
      - "mongo"
    network_mode: host
    env_file:
      - .env
    entrypoint: [ "/run_knowrob_local.sh" ]
