version: "3"
services:
  mongo:
    image: mongo:4.4.3-bionic
    container_name: mongo_container
    ports:
      - 127.0.0.1:27018:27017
    logging:
      driver: "none"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # the KnowRob container
  knowrob:
    container_name: knowrob_container
    build:
      context: .
    depends_on:
      - "mongo"
    environment:
      - KNOWROB_MONGODB_URI=mongodb://127.0.0.1:27018/?appname=knowrob
      - KNOWROB_MONGO_HOST=127.0.0.1
      - KNOWROB_MONGO_PORT=27018
      - KNOWROB_MONGO_USER=root
      - KNOWROB_MONGO_PASS=example
    network_mode: host
    entrypoint: [ "/run_knowrob_local.sh" ]
